### ISSUE TITLE
7) Publicaciones

### ISSUE THREAD

**Issue by dediez1981** [eugesma/ausma#14]
#### Crear migración para la tabla "post_types"
- Atributos:
   - Nombre
   - Crédito

#### Crear ABM de Publicaciones (posts)
- Atributos:
   - Nombre
   - Tipo de post (post_type)
   - Docentes (N:M)
- Formulario:
   - Campo nombre
   - Selector "Tipo de publicación"
   - Selector multiple "Docentes"

================================

Créditos cargar
**Select**
Divulgaciones - Créditos
Técnicas - Créditos * 2
Científicas - Créditos * 3

**Comment by eugesma** [comment]
Crédito por divulgación: 8

**Comment by eugesma** [comment]
@paul18sma issue asignado.

**Comment by eugesma** [comment]
![image](https://user-images.githubusercontent.com/18295285/71522658-63a92b00-28a4-11ea-90df-3f1874f916be.png)

**Comment by eugesma** [comment]
![image](https://user-images.githubusercontent.com/18295285/71522940-93a4fe00-28a5-11ea-8308-2acde6626869.png)

**Comment by eugesma** [comment]
**Teacher**
  has_many :teacher_posts
  has_many :posts, through: :teacher_posts

**TeacherPost**
  belongs_to :teacher
  belongs_to :post

**Post**
  has_many :teacher_posts
  has_many :teachers, through: :teacher_posts

**Comment by Romi-Arg** [comment]
Hola! Actualizo este issue para ver si lo vamos cerrando:

Los campos que tendría que tener este formulario donde el docente detalla sus publicaciones son:

Tipo: Divulgación, Técnica, Científica (lista desplegable asociada a los créditos)
Nombre de la publicación:
Fecha de publicación:
Link o DOI: (este sería el campo donde el docente pone el lugar donde está publicada, nos evitamos que tengan que subir un PDF)
Docentes: (lista)

Este formulario lo carga cada usuario (docentes) no los administradores (gestión).
El link o DOI es lo que nos servirá para auditar la veracidad de lo que se cargó.

**Comment by eugesma** [comment]
Por favor si comentas el issue tratá de reabrirlo así aparece en la lista de pendientes.

**Comment by eugesma** [comment]
El docente debe elegir cuáles otros docentes participaron de la publicación?

**Comment by dediez1981** [comment]
El docente solo cargo lo suyo.

**Comment by eugesma** [comment]
Verificar mejoras en heroku

**Comment by dediez1981** [comment]
Esta bueno euge.
Pueden subir un archivo al drive y mandar el link de esa manera.

**Comment by Romi-Arg** [comment]
Perfecto! 
Ya hice la prueba con una publicación mía y está muy bien. 
Creo que podemos cerrar el issue así que cierro.
