### ISSUE TITLE
4) Transferencias recibidas / Formación docente (teacher formations)

### ISSUE THREAD

**Issue by dediez1981** [eugesma/ausma#15]
Créditos = Horas

**Select 1**
Curso
Taller
Seminario
Conferencia
Simposio

**Select 2**
Asistente - Créditos
Asistente + examen aprobado - Creditos + 50%
Expositor - Creditos + 50%
Organizador - Creditos + 100%
Evaluador - Creditos + 50%

Observaciones
Futuro posibilidad de adjuntar archivo de certificación.

**Comment by Romi-Arg** [comment]
Hola! Actualizo como debería quedar el formulario de "Formación docente/Transferencia recibida":

Formulario de carga por parte de los docentes:

**Tipo:** Curso, Taller, Seminario, Webinar online, Conferencia, Simposio
**Nombre:**
**Fecha inicio:**
**Duración horas:**
**Link a la información del curso:**
**Con certificado en papel o digital:** Si / No _(Hasta que no puedan cargar los certificados en PDF por lo menos que puedan tildar si tienen o no el certificado probatorio)_
**Condición participación:** (lista desplegable asociada a los créditos):
Asistente - Créditos
Asistente + examen aprobado - Créditos + 50%

**Comment by eugesma** [comment]
Verificar en heroku

**Comment by Romi-Arg** [comment]
Lo probé.
Está perfecto.
Si es posible, se podría agregar en la lista de Tipo de curso la opción "Webinar online"?

**Comment by eugesma** [comment]
Listo agregado!

**Comment by Romi-Arg** [comment]
Cerrado entonces!
