### ISSUE TITLE
3) Actividades de extensión

### ISSUE THREAD

**Issue by dediez1981** [eugesma/ausma#18]
Cursos 
Charlas
Seminarios
Conferencia
se asignan docentes, al igual que asignaturas
Los créditos se cargan en horas.
Preparación - Implementación - Evaluación

**Comment by Romi-Arg** [comment]
Hola! 
Molesto de nuevo. Habría que adecuar un poco este ítem (Actividades de Extensión). 

Cada actividad tiene unas horas de implementación y el resto de los valores (preparación y evaluación) se autocalculan de acuerdo a la tablita que pongo más abajo. Los créditos serán entonces la suma de implementación + preparación + evaluación.
![Captura de pantalla de 2020-04-06 16-02-34](https://user-images.githubusercontent.com/24296493/78597073-3bc24f80-7823-11ea-8315-41f9d6c517f2.png)

Entonces creo que el formulario de carga de las Actividades se podría simplificar. A ver qué les parece:
![Captura de pantalla de 2020-04-06 16-23-01](https://user-images.githubusercontent.com/24296493/78597119-4f6db600-7823-11ea-8982-460bd677aaf2.png)

**Comment by Romi-Arg** [comment]
Hola! 
Reabro este ítem por el comentario que había hecho. En esa ocasión comenté y dejé el issue cerrado.

**Comment by eugesma** [comment]
verificar

**Comment by dediez1981** [comment]
Perfecto, el resto es configuración. Lo estuve mirando.
Cierro
