### ISSUE TITLE
5) Gobierno universitario

### ISSUE THREAD

**Issue by dediez1981** [eugesma/ausma#19]

**Comment by dediez1981** [comment]
Consejo Directivo
Secretaría Extensión
Secretaría Ciencia y Técnica 
Director de área  
Departamento
Créditos asignados por cargos, anuales.

**Comment by eugesma** [comment]
Duplicar ABM formaciones. En asignacion de dedicaciones elegir docentes por cada columna de la tabla.

**Comment by eugesma** [comment]
Agregar duracion de funcion

**Comment by dediez1981** [comment]
Crear Item fijos
Secretaría de extensión
Secretaría Academica
Secretaría de Investigación
Área 
Se permite seleccionar un unico docente por Item
