### ISSUE TITLE
6. Proyectos I+D+E+i institucionales.

### ISSUE THREAD

**Issue by eugesma** [eugesma/ausma#23]
Duplicar formaciones. 
Códigos de instancias de aprobación.
Permitir adjuntar archivos PDF. 

**Esperar a relevamiento.**

**Comment by dediez1981** [comment]
Proyecto con posibilidad de asignar docentes
**Cod. Proyecto**.
**Nombre del Proyecto.**
**Tipo de asignación a docente**
Director 
Co-Director 
Integrantes
Colaboradores

**Comment by dediez1981** [comment]
Tipo de proyecto 
ext. 
inv.

Fecha inicio
Fecha de fin

**Comment by eugesma** [comment]
Qué sería "ext" e "inv"? 
Cómo sería el cálculo de los créditos dependiendo del tipo de rol?

**Comment by dediez1981** [comment]
Extensión e investigación

Enviado desde mi iPhone

**Comment by eugesma** [comment]
Cómo sería el cálculo de los créditos dependiendo del tipo de rol?

**Comment by dediez1981** [comment]
El crédito lo carga la secretaria de ciencia técnica.
Va a depender del Tipo de asignación a docente
Director
Co-Director
Integrantes
Colaboradores

**Comment by eugesma** [comment]
Verificar en heroku

**Comment by eugesma** [comment]
Tarea: relevear y definir el cálculo de los créditos para los proyectos.

**Comment by Romi-Arg** [comment]
Disculpen la demora. 
El cálculo de créditos por docente sería una relación entre las horas dedicadas al proyecto y un multiplicador de acuerdo al tipo de participación.

Aquí debajo defino el multiplicador:
Director -- Horas * 2
Co-Director -- Horas * 1.7
Integrantes -- Horas * 1.5
Colaboradores -- Horas * 1.2

Ejemplo:
Docente 1. 
Director del Proyecto X
Horas asignadas al proyecto: 20 horas semanales
Crédito: 20 * 2 = 40 créditos

Pregunta: ¿es posible dejar en la tablita de "variables" el multiplicador abierto por si lo tenemos que cambiar o modificar a futuro?

**Comment by eugesma** [comment]
Bueno ahí estarían los cambios online. No estaría el calculo dinámico en el formulario de asignación de crédito. Cuando terminemos todo agregaremos ese detalle en todos los formularios. Con respecto a la pregunta, se puede modificar el múltiplo del lado de administración del sistema. Testeen si es ese el cálculo que esperan.

**Comment by dediez1981** [comment]
Según la carga de prueba que hice, funciona bien.

**Comment by Romi-Arg** [comment]
Hola!
Disculpen que recién hoy pude hacer la prueba. 
Hay algo que corregir y lamento si me expresé mal cuando lo escribí.

El cálculo de créditos por docente sería una relación entre las horas dedicadas al proyecto y un multiplicador de acuerdo al tipo de participación.

Es decir que en la parte de asignación de créditos al docente le tengo que poder indicar qué tipo de participación tiene y las horas dedicadas. No es que el proyecto tiene una duración en horas, si no que cada docente le dedica X cantidad de horas semanales (que luego multiplicamos de acuerdo al tipo de participación). 

Sería cambiar de acá:
![Captura de pantalla de 2020-06-23 11-49-55](https://user-images.githubusercontent.com/24296493/85419372-641b3980-b548-11ea-95a6-1d1aeef55d2a.png)

Para acá:
![Captura de pantalla de 2020-06-23 11-50-04](https://user-images.githubusercontent.com/24296493/85419410-739a8280-b548-11ea-95bf-2bb62c4c7578.png)

**Comment by eugesma** [comment]
Perfecto ahi entendí

**Comment by eugesma** [comment]
Cambios subidos, testear y confirmar.

**Comment by Romi-Arg** [comment]
Genio!
Perfecto!
Una última.. no veo reflejado en el "Curriculum anual" el ítem proyectos. Puede ser?
Con eso estamos listos para darle closed

**Comment by eugesma** [comment]
Exacto, ahora lo agrego

**Comment by eugesma** [comment]
Ver cambio en heroku

**Comment by Romi-Arg** [comment]
Perfecto! Cerramos.. !
(ya los cargué todos)

**Comment by dediez1981** [comment]
Agregar variable semanas a los proyectos.
Crédito Total=horas*semanas*1,8 (Director)

**Comment by Romi-Arg** [comment]
Amplio un poco el comentario de Damian:

Habría que agregar una columna que sea "Semanas" para que multiplique y aporte al cálculo de los créditos.

Sería entonces:

Crédito total =  horas dedicadas al proyecto * multiplicador de acuerdo al rol * semanas al año

**Comment by eugesma** [comment]
No sería un campo único de cantidad de semanas del proyecto?

**Comment by Romi-Arg** [comment]
Sí. Podría ser así también.

**Comment by eugesma** [comment]
Cambios online. Para ver el cálculo, asignar primero las semanas del proyecto y luego editar las "dedicaciones" de cada docente para que refresque el valor de créditos.

**Comment by Romi-Arg** [comment]
Perfecto! Lo estoy probando. Creo que está bien.
