### ISSUE TITLE
ABM Cargos 

### ISSUE THREAD

**Issue by eugesma** [eugesma/ausma#27]
Los docentes poseen cargos, estos pueden ser:

- Titular (TIT) 
- Asociado (ASO)
- Adjunto (ADJ)
- Ayudante de trabjos prácticos (JTP)
- Ayudante de 1° (AY1)
- Ayudante de 2° (AY2)

**Comment by eugesma** [comment]
Detallar más:
- A qué corresponden estos cargos? 
- Tienen relación a la dedicación?
- Qué modifica en el docente que tenga un cargo u otro?
- Tienen relación a otro item?

**Comment by dediez1981** [comment]
Los cargos corresponden a los docentes, seria bueno ver si es posible que aparezcan en académicas.
![abm](https://user-images.githubusercontent.com/55166129/83983843-0069fd00-a908-11ea-8150-a71758da84c4.png)

**Comment by Romi-Arg** [comment]
**A qué corresponden estos cargos?:** 
Son los cargos docentes que están asignados a cada asignatura.
Ejemplo:
Asignatura: Computación
Docente 1: Damian - Cargo Asisente de Docencia
Docente 2: Eugenio - Cargo Ayudante de Primera (ojalá!). 

Cada docente puede tener más de un cargo por estar en más de una materia. 

**Tienen relación a la dedicación?**
Para simplificar diría que no. 
Ejemplo:
Un docente puede tener una dedicación full time pero tener dos cargos en dos materias distintas. 
Por eso no lo asociaría a la dedicación. 
   
**Qué modifica en el docente que tenga un cargo u otro?**
Es una cuestión jerárquica de la carrera docente. Es como ir ascendiendo. 
El Ayudante de Primera es el menor rango de la carrera docente (menos responsabilidades).
El Profesor es el mayor cargo posible (más trayectoria, antecedentes, etc). 
El cargo debería servir en el futuro para ponderar en los créditos, aunque aún no lo tenemos tabulado. Debería ser un multiplicador. 
   
**Tienen relación a otro item?**
Lo asociaría al ítem "Académica" en cada asignatura ya que el cargo del docente es asignado a cada materia. 
Y pensando en cómo computaría el cargo en la suma de créditos yo haría una tablita (como la que veníamos haciendo de variables) donde cada cargo signifique un porcentaje adicional al cómputo de horas de la asignatura.

Ejemplo (con la captura que hizo Damian):
Uriel Mele - Créditos de la asignatura 173 +  0.50% por ser Profesor = 259

**Comment by Romi-Arg** [comment]
Los cargos docentes son los siguientes: 
![78148317-1be9f080-740b-11ea-8b35-9167d2837bcd](https://user-images.githubusercontent.com/24296493/84031896-ddbdff80-a96c-11ea-8dcd-e516dc9cfa2c.png)

Los pongo aquí de nuevo porque los que están en el inicio de este issue están desactualizados.

**Comment by eugesma** [comment]
Si se puede!
