### ISSUE TITLE
Pantalla Asignar dedicación de asignaturas

### ISSUE THREAD

**Issue by eugesma** [eugesma/ausma#32]
El campo preparación se calcula:
Dictado * 30% (variable de configuración) 

Campo consulta exámenes se calcula:
Suma de dedicaciones (si tiene varias)  * 10% (variable de configuración)

**Comment by dediez1981** [comment]
El campo preparación se calcula:
Dictado * 30% (variable de configuración)

Campo consulta exámenes se calcula:
Suma de dedicaciones (si tiene varias) * 10% (variable de configuración) * semanas de cursado (celda)

**Comment by eugesma** [comment]
Done!
