### ISSUE TITLE
Asistencia

### ISSUE THREAD

**Issue by Romi-Arg** [eugesma/ausma#34]
Agregar ítem que se llena todos los meses con información que procesa administrativa RRHH. 

- Mes
- % Asistencia

En la pantalla principal de cada docente debería verse el % de asistencia de cada mes.

**Comment by eugesma** [comment]
Cómo se contabiliza la asistencia? 
Cada docente tiene diferente dedicación? 
El porcentaje de asistencia de docente depende de qué días debe presentarse, por lo tanto, cada asignatura tendría que tener pre definidos los días de dictado?

A espera de más información.

**Comment by Romi-Arg** [comment]
Sería así:

- Cada docente tiene asignada una dedicación (ej. full time - 8 horas por día). Esto debería salir de la tabla de cargos y dedicaciones de cada uno.
- Desde RRHH todos los meses nos pasarán una planilla que dice: las horas hábiles del mes (en función a los días hábiles) y el cumplimiento registrado por cada docente. 
- A partir de estos datos (días hábiles/cumplimiento) se registra el % de asistencia. 

Cada docente debería ver en su "perfil" el porcentaje de asistencia de cada mes.

**Comment by eugesma** [comment]
Perfecto!
