### ISSUE TITLE
Reuniones

### ISSUE THREAD

**Issue by Romi-Arg** [eugesma/ausma#35]
Hola!
Estoy empezando a cargar las reuniones del 2020 (ahora sí las verdaderas!).
Algunas cosas a ver si se puede simplificar la interfaz de carga. 
Los créditos asignados por cada reunión estarán en función a la duración de la misma. Es decir, si una reunión dura una hora = un crédito para cada docente presente.
Entonces al momento de la carga deberíamos solo completar: duración = crédito y presentes/ausentes. El cómputo de créditos para cada docente será en función a si estuvo o no en la reunión. 

![Captura de pantalla de 2020-03-17 17-41-13](https://user-images.githubusercontent.com/24296493/76900236-b8db5400-6877-11ea-8c6d-9ade699b20d7.png)
![Captura de pantalla de 2020-03-17 17-44-24](https://user-images.githubusercontent.com/24296493/76900250-be389e80-6877-11ea-9a81-cd24efa6c309.png)
![Captura de pantalla de 2020-03-17 17-46-02](https://user-images.githubusercontent.com/24296493/76900253-c0026200-6877-11ea-8179-f31cbb506d62.png)

**Comment by eugesma** [comment]
Done!
