### ISSUE TITLE
Alta y asignación de dedicaciones

### ISSUE THREAD

**Issue by eugesma** [eugesma/ausma#37]
Dar de alta las dedicaciones y luego asignarlas a cada docente según corresponda:

http://ausma.herokuapp.com/dedications

**Comment by Romi-Arg** [comment]
Pregunta:
![Captura de pantalla de 2020-04-01 10-51-48](https://user-images.githubusercontent.com/24296493/78145205-fc50c900-7406-11ea-8585-9f3a90b496f8.png)

**Comment by eugesma** [comment]
Esa es la pantalla de creación de dedicación, la que vos te referís es la de asignación! 
En ese campo deberías colocar por ej: Full Time y 40hrs

**Comment by Romi-Arg** [comment]
Done! 

PD: Quedó "Damian Diez", no me dejó borrarlo. 
![Captura de pantalla de 2020-04-01 11-28-55](https://user-images.githubusercontent.com/24296493/78149340-425c5b80-740c-11ea-83b5-66e5e8e9dfb6.png)

**Comment by eugesma** [comment]
Buenísimo! ahora lo eliminamos.
