### ISSUE TITLE
Re-asignar académicas

### ISSUE THREAD

**Issue by eugesma** [eugesma/ausma#38]
Posterior a completar este [**issue**](https://github.com/eugesma/ausma/issues/37), reasignar a cada docente las horas de "Académicas". Cuidando que estén todos los campos completos para el correcto cálculo de los créditos.

**Comment by Romi-Arg** [comment]
Mientras completamos el issue #37, dejo algunas cosas a ver si se pueden corregir (si no es mucho problema). 

1. Vista de Edición de Asignaturas
![1](https://user-images.githubusercontent.com/24296493/78148146-dfb69000-740a-11ea-9e4b-17b6311878c9.png)

2. Sobre las dedicaciones (quizás se corriga esto cuando asignemos las dedicaciones en #37):
![2](https://user-images.githubusercontent.com/24296493/78148215-fe1c8b80-740a-11ea-8c39-75d0187a0c45.png)

3. Sobre la asignación de **cargos docentes.** No lo agregamos en ningún lado. Creo que lo podemos poner aquí: 
![3](https://user-images.githubusercontent.com/24296493/78148317-1be9f080-740b-11ea-8b35-9167d2837bcd.png)

**Comment by eugesma** [comment]
Perfecto! implementaré esas modificaciones.

**Comment by Romi-Arg** [comment]
Encontré que en este issue #4  ya habíamos mencionado lo de los cargos. 
¿Quizás ya está implementado?

**Comment by eugesma** [comment]
Lo que está de ese issue es la dedicación. Pero no está la tabla de cargos asociada a las dedicaciones. Con esto de los cambios de los nombres tuve que reacomodar la BD y se pudo haber perdido en el transcurso.

**Comment by Romi-Arg** [comment]
Oki!
De todas maneras no encuentro cómo asignar la dedicación a cada docente en función a lo trabajado en #37 
Seguimos...

**Comment by eugesma** [comment]
Buen día, vi que ya pudieron asignar las dedicaciones. Se podría cerrar el issue?

**Comment by Romi-Arg** [comment]
Si. Se podría cerrar. 
Gracias!
