### ISSUE TITLE
Seguimiento anual

### ISSUE THREAD

**Issue by romina-gonzalez-musso** [eugesma/ausma#45]
Deberíamos incluir o pensar alguna manera de que se vean diferenciados los años.
Ya está terminando la carga 2020. Habría que habilitar una pestaña para empezar con la carga 2021. En principio, creo que todos los ítems empezarían en cero. 

Y ver si es posible que se pueda visualizar a modo de registro histórico lo cargado en el 2020 para que vayan quedando todos los años registrados.

**Comment by eugesma** [comment]
lo veo

**Comment by eugesma** [comment]
qué sería habilitar una pestaña para 2021? te referís a ocultar de los listados lo cargado en el año 2020?
